#!/bin/sh

IFACE=$(route -n | tail -n 1 | awk {'print $8'})
IP=$(ip -f inet addr show $IFACE | grep inet| awk {'print $2'} | cut -d/ -f1)

strace -f -o wk-server.strace wk --mode server --server $IP & 
P=$!

sleep 5

wk --mode client --server $IP --sleep 0.2

sleep 0.1

wk --mode client --server $IP --hog 0.2

sleep 0.1

kill $P

